### ISSUE TITLE
Admin section is not working on sub directory meteor setup

### ISSUE THREAD

**Issue by rajpant** [yogiben/meteor-admin#106]
Hi All,
I am using meteor 1.0.2.1 with all the updated package. I am running the meteor application in a sub directory, the URL is something like http://mydomain.com/meteorapp 
The application is running correctly but the admin section is not working http://mydomain.com/meteorapp/admin 
It shows me the error page (404).

Could you please help me out.

Thanks

**Comment by yogiben** [comment]
I'm afraid I have never run meteor in a subdirectory.

**Comment by mpowaga** [comment]
I'll rewrite the router code so that it's possible to set custom admin path.

**Comment by rajpant** [comment]
@mpowaga  Thank you for the information. I'll be waiting for it.

**Comment by yogiben** [comment]
Should have been updated.

Please reopen if still a problem.
