### ISSUE TITLE
sort and filter in datatable view do not work

### ISSUE THREAD

**Issue by obiwarn** [yogiben/meteor-admin#108]
Installed your meteor-starter.
Then I filled in some Posts.
Now in the data table view the sort (clicking column title) and filter (i assume those fields below the table should be filters right?) functionality does not seem to work.

**Comment by slickdev** [comment]
+1 - does not work for me either

**Comment by emptist** [comment]
+ 1 
This is needed when work with a large table

**Comment by anjain** [comment]
Please fix this as filter and sort both are not working.

**Comment by yogiben** [comment]
Should be working now. @mpowaga can you confirm?

**Comment by mpowaga** [comment]
@yogiben Yup.
