### ISSUE TITLE
file upload method

### ISSUE THREAD

**Issue by aj07mm** [yogiben/meteor-admin#110]
currently is there a way to handle file upload?

**Comment by mpowaga** [comment]
You can use [meteor-autoform-file](https://github.com/yogiben/meteor-autoform-file).

**Comment by aj07mm** [comment]
@mpowaga how to apply that in some form of meteor-admin ? 
i didn`t found out

**Comment by mpowaga** [comment]
@aj07mm I think that better way is to define `afFieldInput` type in schema definition.
