### ISSUE TITLE
Use tabular for collection tables?

### ISSUE THREAD

**Issue by aldeed** [yogiben/meteor-admin#114]
I just released [aldeed:tabular](https://github.com/aldeed/meteor-tabular) 1.0, which I think is now pretty full featured. What do you (and others) think about using it for the collection tables in this package? You could provide a single option for passing in a custom Tabular.Table instance, making it simple to override the defaults and get all the benefits of the DataTables library.

I can look into doing a PR, but I'm not sure how soon I'll have time.

**Comment by yogiben** [comment]
Thank you! @mpowaga Please implement

**Comment by mpowaga** [comment]
Already started working on this (see [tabular](https://github.com/yogiben/meteor-admin/tree/tabular) branch).

**Comment by obiwarn** [comment]
Hell yeah! 
Thank you!!

**Comment by yogiben** [comment]
Ready.
