### ISSUE TITLE
Hiding Widgets from Specific Users.

### ISSUE THREAD

**Issue by rwatts3** [yogiben/meteor-admin#115]
Greetings, 

I am curious as to which is the best way to hide a widget from a specific person or a specific role. For instance I want to add a role, or a user which would be my client to have access to the admin panel, but not specific widgets that can control the app. Is there any easy way to do this or would this be custom functionality that I would have to build.

**Comment by mpowaga** [comment]
You can disable the route (with Router.onBeforeAction) but can't hide the widget.

**Comment by rwatts3** [comment]
Thank you @mpowaga for this feedback. I believe I may have to go with an alternative solution. I will try adding a dynamic class of admin to the widget, and depending on the dynamic class update the css so that if the class notAdmin is present, then the widget will have a display:none.

**Comment by aj07mm** [comment]
+1
