### ISSUE TITLE
Why not ask user to login arriving at admin path

### ISSUE THREAD

**Issue by aj07mm** [yogiben/meteor-admin#117]
Hi,
about that, it would be nice to have a input to login when arriving at the admin area already implemented in the package

**Comment by slickdev** [comment]
+1

Does anyone know an easy way to add this in without hacking the package? I'm pretty sure if I make another iron-router route for /admin and set it to redirect to a login page if not logged in, it'll conflict with the existing route.

**Comment by yogiben** [comment]
I've added to the backlog.

https://trello.com/b/QdYMgTRS/meteor-admin
