### ISSUE TITLE
Usage of meteor-pages kills spiderable

### ISSUE THREAD

**Issue by rantav** [yogiben/meteor-admin#118]
See this issue on meteor-pages: https://github.com/alethes/meteor-pages/issues/111
So I wonder - is there a workaround or something I can do to get over that in the context of meteor-admin?...

**Comment by mpowaga** [comment]
We'll get rid of meteor-pages soon.

**Comment by ivankravchenko** [comment]
This is fixed already.
What's problem with alethes:pages anyway? Why we should get rid of this package?

**Comment by ivankravchenko** [comment]
I see, you decided to switch to `tabular`.
I wonder `spiderable` problem fixed, so issue can be closed.
