### ISSUE TITLE
On startup: wrong dashboard item sums 

### ISSUE THREAD

**Issue by obiwarn** [yogiben/meteor-admin#119]
Most collections work fine.

However, one collection always shows 0 items in the dashboard. After I click on it and then return to the dashboard the item sum is correct.

The schema of said collection:

BookingsSchema = new SimpleSchema(

    userId:
        type: String

    spotId:
        type: String

    keyCode:
        type: String

    paymentInstrument:      # credit card / PayPal / coupon
        type: String

    transactionId:
        type: String        # braintrees transaction id / coupon code

    createdAt:
        type: Date
        autoValue: ->
            if (this.isInsert)
                new Date()
            else if (this.isUpsert)
                {$setOnInsert: new Date}
            else
                this.unset()

    updatedAt:
        type: Date
        autoValue: -> new Date()
)

**Comment by yogiben** [comment]
I think we need to remove the collection count entirely. If we make it reactive, the app will publish too much data.

There is also this: https://github.com/percolatestudio/publish-counts

**Comment by mpowaga** [comment]
Solved in 1.1.0.
