### ISSUE TITLE
Can't able to create admin as a package

### ISSUE THREAD

**Issue by sheeshmohsin** [yogiben/meteor-admin#121]
I want to create the configuration codes for admin as a package so that i can remove or add the admin functionality as needed but at attach schema it throwing error.
e.g in this line
Posts.attachSchema(Schemas.Posts)
It says Posts is not defined for attaching the schema because post is defined in the app and this admin code is written as a package. Please suggest some ways to do this or to import the collections defined in my app to the package.

**Comment by yogiben** [comment]
You need to make sure that the collection is defined before the package code is run. I suggest you attache the schema at the same time you define your collection.

**Comment by sheeshmohsin** [comment]
Yeah! I forgot to comment here, i resolved the issue by defining the schema alongwith the collections in the app and putting only the admin configuration in the package.
