### ISSUE TITLE
Cant get app to stop crashing after added this package

### ISSUE THREAD

**Issue by etmarch** [yogiben/meteor-admin#123]
This looks like an awesome start to an admin - the issue is, no matter what I do, as soon as I add the package (via meteor add yogiben:meteor-admin), I get this: "ReferenceError: AdminConfig is not defined", and the app crashes with a code of 8. 

I have the prereqs installed for a while, but maybe I am missing something? Is there a special way to "add" this package, as opposed to others?

Thanks.

Edit: I forgot to mention that I have tried placing this code in several different places (client, server, both, etc..) and I am only met with more errors: ```
@AdminConfig = {
  collections: {
    Posts: {}
  }
};```

**Comment by rogueturnip** [comment]
I'm seeing this error too.

**Comment by mpowaga** [comment]
AdminConfig object should be defined both on the server and client/

**Comment by slickdev** [comment]
Having the same issue. I defined the AdminConfig object on both server and client.

**Comment by slickdev** [comment]
Figured out the problem. Seems that coffeescript isn't loaded as a dependency, and I was under the impression I already had it. Once I added coffeescript and defined the AdminConfig object, it started working for me.
