### ISSUE TITLE
Callstack size exceeded with userId field.

### ISSUE THREAD

**Issue by theduke** [yogiben/meteor-admin#125]
When I add an userId field with autovalue for the current user id, 
admin crashes with the exception: "RangeError: Maximum call stack size exceeded".

I have confirmed that it is this field that causes the error, everything works smoothly when it is not there.

The issue seems to be that this.userId is NULL on the server.
The autovalue code works just fine with regular autoforms for me though.

```javascript
userId: {
    type: String,
    autoValue: function() {
      if (this.isInsert) {
        return this.userId;
      }
      else {
        this.unset();
      }
    }
  },
```

```
W20150129-22:16:16.357(1)? (STDERR) 
W20150129-22:16:16.362(1)? (STDERR) /home/theduke/.meteor/packages/meteor-tool/.1.0.38.ieqxkv++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150129-22:16:16.362(1)? (STDERR) 						throw(ex);
W20150129-22:16:16.363(1)? (STDERR) 						      ^
W20150129-22:16:16.365(1)? (STDERR) RangeError: Maximum call stack size exceeded
```

**Comment by mpowaga** [comment]
Seems to be this autoform [issue](https://github.com/aldeed/meteor-autoform/issues/333).
