### ISSUE TITLE
Trouble creating a new link on meteor-admin

### ISSUE THREAD

**Issue by aj07mm** [yogiben/meteor-admin#126]
```
Meteor.startup(function () {
  if(Meteor.isClient){
  	AdminDashboard.path('/');

	  AdminDashboard.addSidebarItem('foobar',
	    {urls: [
	      { title: 'Statistics', url: AdminDashboard.path('/') },
	    ]});
	
  }
});
```
but no new link is displayed on the admin, am i doing something wrong?

@yogiben

**Comment by mpowaga** [comment]
This path already exists (it is a dashboard page). Try to use something like `AdminDashboard.path('/statistics')`.

**Comment by aj07mm** [comment]
```
if(Meteor.isClient){
  	AdminDashboard.path('/statistics');
	  AdminDashboard.addSidebarItem('foobar',
	    {urls: [
	      { title: 'Statistics', url: AdminDashboard.path('/statistics') },
	    ]});
	
  }

```

tried this but still the same, no new link

**Comment by aj07mm** [comment]
It is a bug, if i add AdminDashboard.addSidebarItem("foo","/error",{icon: "foo"}) in the console and the click on "edit" in some collection or "view all" of user collection the link appears

**Comment by aj07mm** [comment]
and if i refresh the page the links disappear

**Comment by aj07mm** [comment]
@mpowaga

**Comment by aj07mm** [comment]
My solution was to overwrite the rendered function of the template:

```
Template.AdminSidebar.rendered = function(){
  $(".sidebar-menu").append('<li class="treeview"><a href="#"><i class="fa fa-plus"></i><span>Contratos</span><i class="fa fa-angle-left pull-right"></i></a><ul class="treeview-menu"><li><a href="/admin/contratos/pendente"><i class="fa fa-angle-double-right"></i> Pendentes</a></li></ul></li>');
  $(".treeview").tree();
}
```

**Comment by mpowaga** [comment]
Are you sure you don't have any error in console? Please also check which version of `yogiben:admin` is in your project.

**Comment by aj07mm** [comment]
No errors at all.
My version is:

```
yogiben:admin              1.0.9* A complete admin dashboard solution

```

**Comment by yogiben** [comment]
At this version, it should be working. See [meteor starter](https://github.com/yogiben/meteor-starter) for a correctly set up admin.
