### ISSUE TITLE
Assistance re skinning the admin panel.  

### ISSUE THREAD

**Issue by rwatts3** [yogiben/meteor-admin#132]
I have purchased a theme from wraps trap called insomnia.  For cosmetics purposes I would like to know if you or anyone could assist me in re skinning the admin panel so that it looks and feels like the insomnia theme.  

The structure of admin lte is slightly different from the structure of inspinia so this is where I am having the most trouble.  

You can see the inspinia theme by googling wrapstap inspinia.  

Thank you in advance.

**Comment by yogiben** [comment]
Hey @rwatts3 sorry for the late reply.

No advice. It's just hard grind.
