### ISSUE TITLE
Scrolling/Overflow issues

### ISSUE THREAD

**Issue by TheAncientGoat** [yogiben/meteor-admin#135]
The inability to scroll breaks larger forms, and when zoomed in, makes it impossible to see all the records on a screen (and I guess if record contents were long, it would break similarly). (zooming is important on hi-dpi screens in browsers that don't have proper hi-dpi support)

Might fork etc. and make a pull request in a bit, just want to know what would be the preferred way of fixing this.

**Comment by yogiben** [comment]
I still don't fully understand the problem. Could you share a screenshot?

**Comment by TheAncientGoat** [comment]
It seems to be fixed now. It used to be that you couldn't scroll to the bottom of the page and hit the pagination icons.
