### ISSUE TITLE
Delete modal closes instantly

### ISSUE THREAD

**Issue by TheAncientGoat** [yogiben/meteor-admin#136]
Not sure what's the cause of this, but when I try and delete a document, the delete modal pops up and closes instantly. Using the twbs:bootstrap package, and nothing else that could really interfere with that.

**Comment by mpowaga** [comment]
Could you provide more details. Cannot reproduce this bug.

**Comment by raedle** [comment]
@TheAncientGoat I had the same issue until I found this http://stackoverflow.com/questions/13648979/bootstrap-modal-immediately-disappearing and merv's answer. Simply the Modal plugin JavaScript was loaded twice.

```json
bootstrap@0.3.1
twbs:bootstrap@3.3.2
```

So, I removed bootstrap and it works.

```bash
$> meteor remove bootstrap
```

Until now everything seems to be fine.

**Comment by TheAncientGoat** [comment]
This resolved my issue thanks
