### ISSUE TITLE
Making collection associations

### ISSUE THREAD

**Issue by gkodikara** [yogiben/meteor-admin#137]
How do I create collections within your coffee, collection2, autoform syntax. 
I'm trying to create a select input/dropdown with another collections items as options to make a one to one association using something like - 

	flight: 
		type: String
		autoform:
			options: ->
				_.map Meteor.flights.find().fetch(), (flight)->
					label: flight.flightId[0]
					value: flight._id

But I'm getting the error 'Cannot read property 'find' of undefined'. Do I have to make the 'flight' collection available within this collection edit somewhere?

Not sure what I'm missing.

Thanks for any help.

Greg

**Comment by thos37** [comment]
One problem might be that you need to put a Meteor.isClient check into the handler, since the schema is also server side.  The next issue might be that the data isn't there when the autoform is generated, which can be solved by making sure then collection subscription is ready before creating the page.

**Comment by gkodikara** [comment]
I'm doing this within a .coffee file defining the schema for Seats below.

I've made subscriptions within the admin config and published within the collections.coffee file server side. Really am stumped. 

See the seat.coffee file below.

@Schemas = {}
@Seats = new Meteor.Collection('seats');

Schemas.Seats = new SimpleSchema
	seatId:
		type:String
		max: 10

	status:
		type: Boolean

	createdAt: 
		type: Date
		autoValue: ->
			if this.isInsert
				new Date()

	updatedAt:
		type:Date
		optional:true
		autoValue: ->
			if this.isUpdate
				new Date()

	flightId: 
		type: String
		autoform:
			options: ->
				_.map Meteor.flights.find().fetch(), (flight)->
					label: flight.flightId[0]
					value: flight._id

Seats.attachSchema(Schemas.Seats)

**Comment by thos37** [comment]
try sticking an "if Meteor.isClient" block at the beginning of the options function, and then do the _.map inside of that

**Comment by gkodikara** [comment]
No dice. Same error. :(

I'm really confused about how to create regular associations between tables using this system now. If you can't then it makes it pretty unusable. 

I'm sure I'm just going about it the wrong way but it would really help if there was a documented way.

**Comment by taromero** [comment]
@gkodikara did you declare Meteor.flights as a collection anywhere? how? Meteor.flights collection not existing seems to be the problem.

**Comment by gkodikara** [comment]
Hi @taromero 
It's in the adminConfig.coffee file where I've just replaced the original 'Post' collection reference - 

	collections : 
		Flights: {
			color: 'red'
			icon: 'plane'
			tableColumns: [
              {label: 'Flight ID',name:'flightId'}
              {label: 'Flight Time',name:'flightTime'}
            ]
		}
		Seats: {
			color: 'blue'
			icon: 'seat'
			tableColumns: [
              {label: 'Seat ID',name:'seatId'}
              {label: 'Flight ID',name:'flightId'}
            ]
		}

Do I need to be doing it somewhere else?

**Comment by taromero** [comment]
@gkodikara right, you are missing one step. You must first create the collection and then add it to the Admin's collections attribute. You would have to declare the collection like:

```javascript
Flights = new Mongo.Collection('flights')
```

Try adding that line before the `collections` declaration. Take into account that you should declare the `Seats` collection as well.

**Comment by gkodikara** [comment]
@taromero thanks but I already have this within my relevant schemas I believe - 

e.g. - 
@Flights = new Meteor.Collection('flights')  in Flights.coffee
and 
@Seats = new Meteor.Collection('seats') in Seats.coffee

Both followed by the schema for each respectively.

I've moved both of these declarations to the adminConfig.coffee file and I still get the same issue -                    TypeError: Cannot read property 'find' of undefined

Where would you suggest I put it?

Thanks for your help.

**Comment by taromero** [comment]
You have to use new Mongo.Collection instead of Meteor.Collection (I
believe the API changed some time ago). Hope that helps!

**Comment by gkodikara** [comment]
Just tried it - still the same issue. I've tried it in various places and still doesn't see the collection as available...

**Comment by gkodikara** [comment]
@taromero I can share you my project folder if you like...?

**Comment by taromero** [comment]
Sure I can give it a try, do you have it on github?

**Comment by gkodikara** [comment]
Just added - https://github.com/gkodikara/meteor-starter-template :)

**Comment by taromero** [comment]
@gkodikara I just noticed you are calling the collection using 'Meteor.flights.find()' instead of 'Flights.find()'. That should solve your problem. You can check things like this using the meteor shell.

**Comment by gkodikara** [comment]
Hi @taromero I've tried that and although now at least I'm getting a select box output - theres nothing in it.
If you try adding flights first then see if it pulls them into the add seat form. I have about 10 flights in the flights collection but nothing being output in the 'Add Seat' box.

Feels like we're getting closer though...:)

**Comment by gkodikara** [comment]
SOLVED IT - needed the {} within the find().
Not sure why, but it's working now. See below - 

	_.map Flights.find({}).fetch(), (flight)->
						label: flight.flightId
						value: flight._id

Thank you so much for your time and help. :+1:

**Comment by gkodikara** [comment]
Ok - seems to be working now - but the issue I'm having is the values for the _map flights functions won't load in for Seats UNTIL I've viewed all flights/initialised the flight collection...

Any Ideas @taromero ? Anyone?

**Comment by taromero** [comment]
If you are using 1.0.9 you have to use auxCollection, check the readme
sorry I'm from a phone.

**Comment by krishnavedula** [comment]
I've been fighting this for quite some time since yesterday. Thank you for the find({}) suggestion.
