### ISSUE TITLE
Roles / Publication Errors?

### ISSUE THREAD

**Issue by obiwarn** [yogiben/meteor-admin#138]
I updated to the most recent v1.1.0

Now the admin sees only the collections that are published for all clients (not the ones that are listed in the AdminConfig).

**Comment by taromero** [comment]
See https://github.com/yogiben/meteor-admin/issues/124. It seems that a bug was introduced on https://github.com/yogiben/meteor-admin/commit/9747b20e24cc2e24dbac4b3d4447ab5b31cbbd4e.

**Comment by yogiben** [comment]
Fixed now.
