### ISSUE TITLE
auxCollections: Referencing Users in Tables 

### ISSUE THREAD

**Issue by obiwarn** [yogiben/meteor-admin#139]
I use this table in my AdminConfig:

        Bookings:
            auxCollections: ['Spots']
            tableColumns: [
                {label: 'User', name: 'userId', collection: 'Users'}
                {label: 'Spot', name: 'spotId', collection: 'Spots', collection_property: 'shortName'}]

The auxCollection reference for Spots works great.
Showing the user email does not work in many cases. It seems kind of unpredicateble, like if we miss a "waitOn: Users" in the router or something.

However, it always works when I visit the Users table in the admin view first (and then visit the Bookings table).

**Comment by zaklampert** [comment]
@obiwarn  I had to globally waitOn the auxCollection (Spots, in your case) in my Router.configure in order for the relationship to show up in the admin collection (Bookings).

```js
Router.configure({
waitOn:function(){
return [
Meteor.subscribe('spots')
]
}
})
```
