### ISSUE TITLE
Integration with tap:i18n-db

### ISSUE THREAD

**Issue by slickdev** [yogiben/meteor-admin#141]
Is there a way to integrate tap:i18n-db into the admin panel? I need to be able to manage translations from within the admin panel. 

If this is possible, can anyone explain how to go about it? Thanks in advance.

**Comment by rdewolff** [comment]
Wondering exactly the same. Just noticed that a recent commit on tap:18n-db mentions yogiben:admin. Cf https://github.com/TAPevents/tap-i18n-db/commit/ba983bccd01611bfb99f93e5892892d987a105e3#diff-02f0b547c2779d25cff89672135f20e3R3

Any info/doc/direction to point out how to use this? Would be great! Maybe @theosp can help.

Cheers

**Comment by yogiben** [comment]
Added it to the trello backlog https://trello.com/b/QdYMgTRS/meteor-admin
