### ISSUE TITLE
Allow/Deny Rules

### ISSUE THREAD

**Issue by slickdev** [yogiben/meteor-admin#142]
Is there any way to set Allow / Deny rules for CRUD functions within meteor admin? I can't find any way to set restrictions within the admin panel, seems that all inserts/updates/deletes are accepted.

For my particular use case I have admins set to different geographical regions. Each admin should only be able to see and manipulate their own region.

**Comment by adamwong246** [comment]
+1

**Comment by yogiben** [comment]
Good point. Not sure how to set this up exactly but will add to trello.
