### ISSUE TITLE
Collection's documents are not displayed.

### ISSUE THREAD

**Issue by seuqaj114** [yogiben/meteor-admin#145]
I have the following code
```javascript

AdminConfig = {
	nonAdminRedirectRoute: 'campaignsList',
	name: "Campaign",
	collections:{
		Campaigns:{}
	}
}

Schema = {}

Schema.Campaigns = new SimpleSchema({
	brand:{
		type:String
	},
	prize:{
		type:String
	},
	rules:{
		type:String
	},
	groups: {
	    type: [Object]
	},
	"groups.$.names": {
	    type: String
	},
	"groups.$.votes": {
	    type: Number
	},
	"groups.$.voters":{
		type: [Object],
		optional: true
	}
});

Campaigns.attachSchema(Schema.Campaigns);
```
and in the admin panel it says I have 0 Campaigns, even though I know I have 3 (they are displayed across the rest of the website, aswell as the db shell). In the current settings, I can even add a Collection through mongo-admin, but it is not displayed. The Users panel, however, works normally, showing all the users and allowing edits, even though I didn't configure it.

Am I missing something that allows mongo-admin to show all the Campaigns?

Thanks in advance

**Comment by devyg** [comment]
See issue #124 .

**Comment by yogiben** [comment]
Fixed now
