### ISSUE TITLE
Collections doesn't show any items after 'meteor remove autopublish'

### ISSUE THREAD

**Issue by Firfi** [yogiben/meteor-admin#146]
Hey,

how to reproduce:

1) meteor remove autopublish

2) add publishing script in server/model/data.js :

```javascript
Meteor.startup(function () { // tried without meteor startup
  Meteor.publish('PracticeItems', function(){ // I added multiple here just to check that I don't have problems with casing
    return PracticeItems.find();
  });

  Meteor.publish('practiceItems', function(){
    return PracticeItems.find();
  });

  Meteor.publish('practiceitems', function(){
    return PracticeItems.find();
  });
});

```

3) have config in lib/admin.js

```javascript
AdminConfig = {
  adminEmails: ['igor.loskutoff@gmail.com', 'igor@loskutoff.com'],
  collections:
  {
    PracticeItems: {
      tableColumns: [
        ...
      ]
    }
  }
};
```

4) visit any application page except /admin and do PracticeItems.findOne() in console. It returns an object.

5) visit /admin and do PracticeItems.findOne() in console. It returns undefined.

6) meteor install autopublish

7) visit /admin and do PracticeItems.findOne() in console. It returns an object.

I tried last version presuming it is https://github.com/yogiben/meteor-admin/issues/124 issue but it's not as downgrading to `yogiben:admin@=1.0.9` doesn't have an effect.

8) collections initialized in lib/ with `PracticeItems = new Mongo.Collection("practiceItems");`

9) Meteor 1.0.3.1

**Comment by Firfi** [comment]
If I do Meteor.subscribe('PracticeItems', function() {console.warn(PracticeItems.findOne())}) in console at path /admin collection items appears.

**Comment by Firfi** [comment]
UPD: I think I just using publish/subscribe feature wrong. I.e. if I add Meteor.subscribe('PracticeItems', function() {}); in some common code on client/ admin interface works as expected, i.e.

client/main.js
```
Meteor.subscribe('PracticeItems', function() {});
```

Is it right approach?

**Comment by rwatts3** [comment]
Partially correct. 
Another thing to consider is when you are using routes, you have to tell the router to wait on that data before rendering the view. So the correct syntax would be as follows. 
`
waitOn: function() {
      return [Meteor.subscribe('PracticeItems', this.params.collection)];
`

**Comment by Firfi** [comment]
Thanks for the advice! Will use.
