### ISSUE TITLE
AutoForm hooks

### ISSUE THREAD

**Issue by mkarliner** [yogiben/meteor-admin#151]
I'd like to be able to use either Autoform hooks, so I can do some processing after an insert or update, or to use matb33:collection-hooks for the same purpose.

In the case of Autoform hooks, I don't know the canonical names for the forms so I can add hooks to them.

As far as collection-hooks goes, I have a collection Feeds, defined and working in meteor-admin,
and a before insert thus:

Meteor.startup(function(){
	Feeds.before.insert(function(userId, doc) {
		console.log("New Feed: ", userId, doc);
	});
});

The hook works if I manually do:

Feeds.insert({subscription: "sadf", title: "dsfsadf", name: "asdf"});

I get: 

feeds.js?f8561b375135b6cdcc257d930d7af91126b9590c:10 New Feed:  EgzbLGjK66ENpishb Object {subscription: "sadf", title: "dsfsadf", name: "asdf"}

But does not fire when I add a Feed with admin.

Any clues?

Mike

**Comment by yogiben** [comment]
@mpowaga could we programatically give each form an id?

**Comment by mpowaga** [comment]
@mkarliner Insert form have `admin_insert` id and update form `admin_update`. You can use these ids to add your own hooks. If you want to check for which collection the hook has been called you can use `this.template.data.collection`.

**Comment by reduxdj** [comment]
Wow, I'd love to see an example of this, where does that code go?

**Comment by mpowaga** [comment]
```javascript
AutoForm.hooks({
  admin_insert: {
    onSuccess: function () {
      if (this.template.data.collection === Posts) {
        console.log('successfully added Post');
      }
    }
  }
});
```
