### ISSUE TITLE
Using collection-helpers requires duplicate table column definition for a field

### ISSUE THREAD

**Issue by raedle** [yogiben/meteor-admin#155]
Hi there!

I appreciate your great work on this!!

At the moment, I am working with the master branch of yogiben:admin. It is awesome to actually being able to define custom table column templates and it works like a charm.

However, if I use collection-helpers it is necessary to define a 'temporary' column for the same field because otherwise the property is not accessible/subscribed in the collection helper function. For instance, in the example below the field 'type' is only in the doc and accessible through 'this' in collection helper if explicitly defined as below ({ label: 'Type2', name: 'type' }).

AdminConfig definition for Publication collection.
```javascript
Publications: {
  color: 'white',
  icon: 'university',
  tableColumns: [
    { label: 'Type', name: 'publicationType().title' },
    { label: 'Type2', name: 'type' },
    { label: 'Title', name: 'title' },
    { label: 'Date', name: 'date' },
    { label: 'User', name: 'owner', template: 'userEmail' }
  ]
}
```

Here is the collection-helper.
```javascript
Publications.helpers({
  publicationType: function () {
    if (this.type) {
      try {
        return PublicationTypes.findOne(this.type);
      }
      catch (error) {
        return undefined;
      }
    }
  }
});
```

**Comment by ivankravchenko** [comment]
Hi, @raedle.
I suggest you to use extraFields functionality:
```coffee
@AdminConfig =
	collections:
		TestItems:
			tableColumns: [
				{ label: "Image", template: "imageColumn" }
				{ label: "Title", name: "title" }
			]
			extraFields: ['image']
```

**Comment by tmunzar-jfish** [comment]
@ivankravchenko 
I have the exact same issue. None of my helper function retrieved values are showing up in a collection's index table columns (they show up perfectly fine when you edit and access then individually).

I don't understand what this extraFields option is doing, and how am I to use it?

Here's my snippet

```coffeescript
@AdminConfig =
	name: 'Cinema'
	collections:
		Movies:
			icon: 'film'
		MovieTimings:
			icon: 'clock-o'
			tableColumns: [
					{ label:'Movie', name:'movieTitle()' }
					{ label:'Showtime', name:'show_time' }
			]
```
```javascript
MovieTimings.helpers({
  movieTitle: function() {
    if(this.movie_id){
      return Movies.findOne(this.movie_id).title;
    }
  });
```

**Comment by ivankravchenko** [comment]
@tmunzar-jfish, you have removed `insecure` and `autopublish`, correct?

To display movie title in MovieTimings table, you have to configure `publish-composite` subscription:
```coffee
@AdminConfig =
    name: 'Cinema'
    collections:
        Movies:
            icon: 'film'
        MovieTimings:
            icon: 'clock-o'
            tableColumns: [
                { label: 'Movie', name: 'movieTitle()' }
                { label: 'Showtime', name:'show_time' }
            ]
            children: [
                find: (movieTimingDoc) ->
                    if SimpleSchema.RegEx.Id.test movieTimingDoc.movie_id
                        Movies.find movieTimingDoc.movie_id
                    else @ready()
            ]
```
This will ensure that related Movie is loaded.
I think then your helper will work.

**Comment by tmunzar-jfish** [comment]
@ivankravchenko This is not helping me. I've added the `publish-composite` package and everything.
And yes, I have removed `insecure` and `autopublish`.

**Comment by ivankravchenko** [comment]
@tmunzar-jfish, would you mind to share project (or simplified, but working reference project) on github, so I can try help you?

**Comment by tmunzar-jfish** [comment]
@ivankravchenko I've shared it with you. Your help is much appreciated!

**Comment by ivankravchenko** [comment]
@tmunzar-jfish, done, pushed d3c3587d1a366025f4fe979bb4dddf343a1393e3 to your repo.

**Comment by tmunzar-jfish** [comment]
@ivankravchenko Thanks so much!

**Comment by stivaugoin** [comment]
I have the same issue. What is the solution?

**Comment by pozylon** [comment]
same here, is there any workaround?

**Comment by pozylon** [comment]
okay, i've seen the proposal with extraFields from @ivankravchenko worked for me, that is the solution and in my opinion quite a clean one.

**Comment by brylie** [comment]
Yep, the `extraFields` setting worked for me. It seems to include the field in the publication/subscription behind the scenes, while not showing it in the table. Is this documented?

**Comment by DumpOfTheVar** [comment]
passfrase for pivate key

**Comment by mpowaga** [comment]
Yes it is in the docs.
