### ISSUE TITLE
Remove accounts-password requirement

### ISSUE THREAD

**Issue by ndarilek** [yogiben/meteor-admin#158]
I wanted to ditch accounts-password from a project and rely exclusively on other services, but removing it didn't work. In looking at dependencies on Atmosphere, I see that this package requires it.

Would it be possible to eliminate this dependency and just not show password fields if the user hasn't installed accounts-password?

**Comment by yogiben** [comment]
Coming in upcoming version

https://trello.com/b/QdYMgTRS/meteor-admin
