### ISSUE TITLE
Admin route not working

### ISSUE THREAD

**Issue by afuhrtrumpet** [yogiben/meteor-admin#162]
I followed the configuration instructions in the README up until the point where it instructed me to go to '/admin', and the admin route does not do anything (just goes to the main page). What could I be doing wrong here? For reference, the issue is in https://github.com/CWDG/design-circle/tree/admin

**Comment by AleksNFedorov** [comment]
+1. Unable to get it worked following 'Getting started'

After step 1 application does not start
After step 2 I get message - "You need to be an admin to view this page"

**Comment by afuhrtrumpet** [comment]
All I needed to do was create an index route for this to go away.
