### ISSUE TITLE
Atmosphere package issue (no publications, searching, sorting, etc.)

### ISSUE THREAD

**Issue by ivankravchenko** [yogiben/meteor-admin#181]
Dear @yogiben and collaborators,
there is a problem with Atmosphere package (which can be installed with usual `meteor add yogiben:admin`):
1. When `autopublish` and `insecure` are removed, no data is displayed at all, so people are workarounding with some custom and incomplete `Meteor.publish`-es.
2. Sorting, searching, pagination, objects counts having issues too.

Several related issues: #170, #145, #124.

The workaround is to install package locally. Almost all functionality comes up.
So I request to *maintain package consistency*, so it can be usable by more people.

**Comment by dutchakdev** [comment]
+1

**Comment by masca88** [comment]
+1

**Comment by yogiben** [comment]
Should be fixed now.

**Comment by ivankravchenko** [comment]
@yogiben, thank you!
