### ISSUE TITLE
#{collection} in url after new/edit element in collection

### ISSUE THREAD

**Issue by bogdanrn** [yogiben/meteor-admin#191]
After i add or edit an element, i am redirected to /admin/#{collection} and in the console i get this 2 errors:

>Exception in template helper: TypeError: Cannot read property 'templates' of undefined
>Exception in template helper: TypeError: Cannot read property 'omitFields' of undefined

On the server side, i don't have any output. I also noted that the records are inserted/updated

**Comment by mpowaga** [comment]
Fixed thanks to this [PR](https://github.com/yogiben/meteor-admin/pull/186). Should be published on Atmosphere soon.
