### ISSUE TITLE
Multiple Edit / Delete buttons

### ISSUE THREAD

**Issue by malpaso** [yogiben/meteor-admin#193]
I'm getting multiple edit / delete buttons showing for every row when I view a collection. For example:

![image](https://cloud.githubusercontent.com/assets/554049/7695733/56998d48-fe37-11e4-82e9-fab4968729cd.png)

**Comment by iwoork** [comment]
+1

**Comment by mpowaga** [comment]
I believe this is already fixed by this [commit](https://github.com/yogiben/meteor-admin/commit/b3d81ef32fcff94bc7f270c3107932b125b337a2). Should be published on Atmosphere soon.
