### ISSUE TITLE
AdminConfig: collection helpers bug (table relations)

### ISSUE THREAD

**Issue by obiwarn** [yogiben/meteor-admin#196]
"spot" is a collection helper function that uses "spotId" to show the name of the spot.

`Bookings.helpers(
    spot: ->
        Spots.findOne(this.spotId).shortName
)`

When I remove the row that uses spotId, the helper does not work anymore (shows "undefined" in the table).

See below my config:
      
`Bookings:
            tableColumns: [
                {label: 'Spot', name: 'spotId'}
                {label: 'Name', name: 'spot'}`

**Comment by mpowaga** [comment]
Use `name: 'spot()'` instead of `name: 'spot'`.

**Comment by obiwarn** [comment]
Sorry for testing so late.

Unfortunately using spot() does not help.

For any "virtual value" column I need to include the corresponding Id columns in the table to work.

**Comment by nschulte** [comment]
I'm having this issue as well (v1.2.2). Collection helpers don't seem to be called.
