### ISSUE TITLE
Sort & Search does not work for relations via collection helper

### ISSUE THREAD

**Issue by obiwarn** [yogiben/meteor-admin#197]
Columns with data from collection helpers cannot be sorted nor searched for.

**Comment by mpowaga** [comment]
These are virtual fields and are not saved to the database. It makes it impossible or very hard to search/sort them.

**Comment by donhavey** [comment]
Exposing Tabular's 'data' attribute for a column would allow the user to override this behavior, even if it is a little glitchy. This would be helpful in instances where you don't care about the alphabetical order of a collection helper, but would like to group data by similar relational _ids, e.g. sort a Students table by Instructor (non-alphabetical).
