### ISSUE TITLE
can't login?

### ISSUE THREAD

**Issue by dcsan** [yogiben/meteor-admin#20]
I added the below to a file as `both/app.js`

```
AdminConfig = { 
  collections: { 
    Players: {}, 
    Users: {} 
  } 
}
```

and did a `meteor reset`
I am logged in 
checked there is a single user created in mongo
u = Meteor.user().profile
Object {name: "Dc Collier"}

but i still get "you need to be an admin to view this page" error message.

**Comment by almogdesign** [comment]
I'm getting this issue which I believe is because I'm using my own custom roles

**Comment by craigmacgregor** [comment]
I ended up logging into the mongodb console and wiping the users and roles collections by:

```bash
db.users.remove({})
db.roles.remove({})
```

Then putting this script in one of my server script files to generate a new user and make them an admin.

```javascript
var id = Accounts.createUser({
    email: "craig.b.macgregor@gmail.com",
    password: "pakage29",
    profile: { name: "craig.b.macgregor" }
});
```
Roles.addUsersToRoles(id, ['admin'], 'default-group');
