### ISSUE TITLE
View meteor-roles collection?

### ISSUE THREAD

**Issue by gazzer82** [yogiben/meteor-admin#210]
I am trying to get the roles collection visible in meteor-admin and failing.

I have created and attached a schema to Meteor.roles with no error, but when i add either roles or Roles to the collections config i get an error stating Error: roles is not in the [object global].

I'm guessing it's not picking the roles collection up for some reason, any ideas?

Thanks

Gareth

**Comment by brylie** [comment]
From what I can tell, the Roles collection is only [defined on the Server](https://github.com/alanning/meteor-roles/blob/master/roles/roles_server.js#L9). For the Admin UI to display collections, the collection may need to be defined on client and server.

**Comment by brylie** [comment]
On further inspection, there does seem to be a [Meteor.roles collection](https://github.com/alanning/meteor-roles/blob/master/roles/roles_common.js#L14] published on both the client and server.

**Comment by brylie** [comment]
Try adding the following to your `adminConfig`:

```
'Meteor.roles': {
  color: 'green',
  tableColumns: [
    {label: 'Name', name: 'name'}
  ]
}
```

**Comment by brylie** [comment]
You will also need the following schema:

```javascript
var RolesSchema = new SimpleSchema({
  name: {
    type: String,
    label: 'Name'
  }
});

Meteor.roles.attachSchema(RolesSchema);
```

**Comment by gazzer82** [comment]
Yup that got it thanks, i was all the way there apart from the single quotes around 'Meteor.roles'

**Comment by baberuth22** [comment]
I still get the following error when trying to select a role for a user:

SERVER

exception while invoking method 'adminAddUserToRole' Error: After filtering out keys not in the schema, your modifier is now empty

**Comment by aposidelov** [comment]
@baberuth22 https://github.com/alanning/meteor-roles/issues/178
