### ISSUE TITLE
Document 'extraFields' configuration option

### ISSUE THREAD

**Issue by brylie** [yogiben/meteor-admin#211]
There are patterns where users want to include a field in a publication, but not necessarily have it appear in the admin table (such as for collection helpers using ID fields reported in issue #155 ).

To this end, the `extraFields`option is available, but seems to be undocumented. Please document the `extraFields` configuration option.

**Comment by mpowaga** [comment]
We are going to update the docs this week.

**Comment by morgunder** [comment]
i'm not sure where the documentation says exactly how to use this (vs mentioning the field name itself), but this is what worked for me.

extraFields: [ "child.field", "field2" ],
