### ISSUE TITLE
Object removal hook

### ISSUE THREAD

**Issue by gazzer82** [yogiben/meteor-admin#214]
I have created some hooks on admin_insert and admin_update for onSuccess, which are working fine. However i also need a hook for when an object is deleted, but i can't find the correct config.

I've tried the following, which according to auto-form should work, but it doesn't get called.
```
var hooksObject = {

  // Called when any remove operation succeeds
  afterRemove: function(id) {
    console.dir('Removed' + id);
  },
};

AutoForm.addHooks(null, hooksObject);
```

Any help appreciated!

Thanks

**Comment by mpowaga** [comment]
Remove operations are done without autoform. Instead modal is shown. Check the [adminDeleteBtn](https://github.com/yogiben/meteor-admin/blob/master/lib/client/html/admin_templates.html#L163) and [AdminDeleteModal](https://github.com/yogiben/meteor-admin/blob/master/lib/client/html/admin_layouts.html#L46) templates.

**Comment by gazzer82** [comment]
Thanks for the info, i ended up doing this with meteor-collection-hooks in the end as it seemed cleaner.
