### ISSUE TITLE
Unable to add custom page

### ISSUE THREAD

**Issue by gazzer82** [yogiben/meteor-admin#221]
I am trying to add a custom page to meteor-admin and failing miserably.

The template is called adminTools, and is in the client files directory.

So in i have this in me startup file:

````
Meteor.startup(function() {
    AdminDashboard.addSidebarItem('Admin Tools', AdminDashboard.path('adminTools'), { icon: 'plus' });
});
````

Then in my iron router config i have:

````
Router.route('adminTools', {
  path: AdminDashboard.path('adminTools'),
  name: 'adminTools',
  controller: 'AdminController',
  onAfterAction: function () {
    Session.set('admin_title', 'Analytics');
  }
})
````

I see the link in meteor-admin sidebar, but clicking it takes me to a standard collection view and not the custom page i have setup.

Obviously missing something, help greatly appreciated.

Thanks

Gareth

**Comment by mpowaga** [comment]
It's fixed already. We will release the new version this week.

**Comment by gazzer82** [comment]
Hi @mpowaga did this get fixed?

**Comment by gazzer82** [comment]
Actually just tested this and seems to be working as expected after the latest update, thanks!
