### ISSUE TITLE
Error after latest release

### ISSUE THREAD

**Issue by aeleftheriadis** [yogiben/meteor-admin#223]
I am keep getting the following error after latest update

 => Errors while adding packages:

While selecting package versions:
error: unknown package: mfactory:admin-lte

**Comment by mpowaga** [comment]
Are you using version from the repo? We still are working on the new version. Please install from Atmosphere.

**Comment by aeleftheriadis** [comment]
Ok I will try to install 1.2.0 on a clean project. Thanks
