### ISSUE TITLE
Broken styles - no such package "mfactory:admin-lte"

### ISSUE THREAD

**Issue by pcorey** [yogiben/meteor-admin#227]
It looks like this commit broke the styling for the admin dashboard. There is no such package "mfactory:admin-lte".

https://github.com/yogiben/meteor-admin/commit/13d5e5646dfbf667a6d7b6de933cf31a4c6d26a5

**Comment by mpowaga** [comment]
Please use 1.2.0 version from the Atmosphere. Repo version is still under development.
