### ISSUE TITLE
browser is blocking meteor-admin due to HTTPS rules

### ISSUE THREAD

**Issue by vladejs** [yogiben/meteor-admin#237]
When i go to my app over https, the browser console says:

Mixed Content: The page at 'https://my.website.url/' was loaded over HTTPS, but requested an insecure stylesheet 'http://my.website.url/packages/mfactory_admin-lte/css/AdminLTE.min.css'. This request has been blocked; the content must be served over HTTPS.

So thanx to that error, /admin route doesn't work at all

**Comment by bogdanrn** [comment]
i have the same issue

**Comment by vladejs** [comment]
Yes, you fixed it @bogdarn. I did the same on modulus and worked perfectly. I'll close the issue.
