### ISSUE TITLE
Disable removing last admin

### ISSUE THREAD

**Issue by jasonszhao** [yogiben/meteor-admin#245]
I accidentally removed my admin privileges; now no one can access the dashboard!

**Comment by mordra** [comment]
It's very easy to do this yourself, you can put in a collection update hook to disable all updates that removes the role from yourself. Also easy to put it back by directly changing collection or via mongo toys.

**Comment by jasonszhao** [comment]
Thank you! I didn't realize how *flexible* meteor-admin is
