### ISSUE TITLE
"No data available in table" for Users

### ISSUE THREAD

**Issue by sgccarey** [yogiben/meteor-admin#255]
I can't seem to get any data to display in the User table. The Dashboard widget shows that I have 7 users, and I can view the users in my browser console with "Meteor.users.find().fetch()".

When I open the Users view from the dashboard I get an empty table with the message: 
>"No data available in table"

and in the browser console:

> Exception from Tracker recompute function:
> debug.js:41 TypeError: Cannot read property '0' of undefined
>    at AdminTables.Users.Tabular.Table.columns._.union.render (startup.coffee:58)
>    at jquery.dataTables.min.js:15
>    at Object.b.fnGetData (jquery.dataTables.min.js:9)
>    at w (jquery.dataTables.min.js:14)
>    at Ia (jquery.dataTables.min.js:21)
>    at I (jquery.dataTables.min.js:13)
>    at ub (jquery.dataTables.min.js:36)
>    at jquery.dataTables.min.js:33
>    at Template.tabular.rendered.ajaxOptions.ajax (tabular.js:68)
>    at qa (jquery.dataTables.min.js:33)

I have tried all sorts of publications and none, have used the standard schema from aldeed and have tried it without. All of my other Collections are displayed without issue. Please help.

**Comment by daloev71** [comment]
Hi, I had the same issue. It was because I was creating an incomplete user (no email) manually using Meteor.users.insert instead of using Accounts.createUser  with username, email, password and profile.

**Comment by sgccarey** [comment]
That was it, thanks.

**Comment by morrismukiri** [comment]
It doesn't work when you add facebook users

**Comment by sgccarey** [comment]
@morrismukiri, I got around this by adding a dummy email account during the account creation:

    Accounts.onCreateUser(function(options, user) {

        if (!user.emails) {
            user.emails = [{address: user.username + "@facebook.user", verified: false}];
        }
    }

**Comment by morrismukiri** [comment]
I did the same, I used the email in facebook profile as the email, but it still didn't work. I also add other info to the user profile.  When I remove the facebook users from the users collection, the remaining users appear in the admin

**Comment by niranjans** [comment]
+1. Not working with Facebook users

**Comment by morrismukiri** [comment]
I ended up hiding the users collection from admin and adding my own users collection with the fields I needed.
The `Accounts.onCreateUser` does not work with facebook redirect.

**Comment by jlourenco** [comment]
Here's how i did it:

```javascript
Accounts.onCreateUser(function(options, user) {
    if (!user.emails) {
        user.emails = [{address: user.services.facebook.email, verified: false}];
    }
    return user;
});
```
