### ISSUE TITLE
Can't change skin color

### ISSUE THREAD

**Issue by ashutoshrishi** [yogiben/meteor-admin#268]
Adding

    dashboard: {
      	homeUrl: '/dashboard',
        skin: 'black'
	}

still doesn't change the dashboard theme to black, but instead stays on the default blue.
I have tried green as well, but the blue theme stays. 

On Meteor 1.1.0.3, meteor-admin: 1.2.2

**Comment by jlourenco** [comment]
Same here.

Meteor 1.1.0.2, meteor-admin: 1.2.0

**Comment by AramilRey** [comment]
Same here!

```javascript
	dashboard: {
		skin: 'red-light'
	}
```

Meteor version: 1.2.1 , admin version: 1.2.3

**Comment by elainhelen** [comment]
AdminConfig = {
	skin: 'red-light',
} 
Changes the theme for me.

**Comment by elainhelen** [comment]
It works.
The skin setting should put outside of the dashboard. 
AdminConfig = {
	skin: 'red-light',
       //....
	dashboard: {
    	homeUrl: '/admin',
	}
};

**Comment by snamoah** [comment]
@elainhelen great!

**Comment by snamoah** [comment]
closing issue now
