### ISSUE TITLE
template.body.events doesn't works!

### ISSUE THREAD

**Issue by paulo9** [yogiben/meteor-admin#275]
if(Meteor.isClient){
Template.body.events = {
     'click body': function (event) { 
        console.log("test");
     }
  };
};

**Comment by macrozone** [comment]
This is the meteor-admin community package and not the Meteor-repository.

by the way, Template.body.events is a function that receives an object.

`````
if(Meteor.isClient){
   Template.body.events({
      'click body': function (event) { 
          console.log("test");
      }
  });
}
``````
