### ISSUE TITLE
Compatibility with Meteor 1.2?

### ISSUE THREAD

**Issue by ndarilek** [yogiben/meteor-admin#277]
Looks like various dependencies make it impossible to run this on Meteor 1.2. In particular, less and at least one additional package appear to require upgrades.

Any plans to make this run under 1.2? I can't upgrade any projects using this package because of its dependency constraints.

Thanks.

**Comment by TimoRuetten** [comment]
+1

**Comment by pozylon** [comment]
+1

**Comment by pascajer** [comment]
+1

**Comment by zylootino** [comment]
+2

**Comment by CaptainN** [comment]
I have a pull request up for this. #276

For now you can download either a fork, or just a unzip an archive of this repo (or mine) and place it in your packages folder. Then make sure the LESS reference is updated to include the new required version number: `less@2.5.0`.

**Comment by derdaumen** [comment]
+1

**Comment by macrozone** [comment]
it is now merged and seems to work with meteor 1.2. Close?

**Comment by CaptainN** [comment]
There is actually a second issue. The less patch gets the package to install, but the data tables in the collection list pages are not working correctly in meteor 1.2 if the collection has any records.

**Comment by thomasspiesser** [comment]
is it the same as #280 ? can anyone still use this package with 1.2?

**Comment by CaptainN** [comment]
The issue I mentioned above about the data tables is the same as #280. The same issue was fixed in [flow-db-admin](https://github.com/sachinbhutani/flow-db-admin/) - maybe someone could figure out what fixed it there, and apply the same fix here?

**Comment by cagrigunal** [comment]
+1

**Comment by MartinBucko** [comment]
+1

**Comment by TimoRuetten** [comment]
Does the update is working for anyone ? I have problems with modulus because meteor isnt updated to the last version and until now my application isnt working correctly because of the less problem.

**Comment by CaptainN** [comment]
Please clone my repo to your local packages directory and see if my fix for the collection views works for you: https://github.com/CaptainN/meteor-admin/

**Comment by Maay** [comment]
@CaptainN thank you!

**Comment by CaptainN** [comment]
I redid my fork (because I screwed it up - still new to fork and PR workflow). The new PR #289 has the same fix and also a fix for the Users table.

**Comment by CaptainN** [comment]
Oh, it looks like my original PR #284 has the fix too. I think I'm starting to understand how the PR system works. :-)
