### ISSUE TITLE
Can NOT install yogiben:admin

### ISSUE THREAD

**Issue by emiliano-viada-developer** [yogiben/meteor-admin#278]
When I run meteor add yogiben:admin, I get:

While selecting package versions:
error: Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.0_2.
Constraints on package "less":
* less@=2.5.0_2 <- top level
* less@1.0.11 <- yogiben:admin 1.2.2

Anyone knows how to fix it?

**Comment by macrozone** [comment]
See https://github.com/yogiben/meteor-admin/issues/277

**Comment by emiliano-viada-developer** [comment]
+1. That works, thanks @macrozone
