### ISSUE TITLE
Version without bootstrap

### ISSUE THREAD

**Issue by ayonix** [yogiben/meteor-admin#28]
Hey, I don't really want to import bootstrap as well in my application.
Would it be possible to make a version without bootstrap as dependency?

**Comment by yogiben** [comment]
The difference between `cfs` and `admin` is that `admin` requires a much more complex UI. I wanted to give users something beautiful so I used LTE Admin which is based on bootstrap.

I'm happy to accept a PR.

**Comment by Geen-Henk** [comment]
Maybe add an option in the config to "lazyload" Bootstrap and/or FontAwesome. 

To give you an impression:

**Config**
```coffeescript
@AdminConfig = 
  lazyLoad: {
    bootstrap: true
    fontawesome: false
  }
```

**Router**
```coffeescript
@AdminController = RouteController.extend
  onBeforeAction: ->
    
    # Some stuff omitted..
    
    if AdminConfig.lazyLoad.bootstrap
      $("<link/>", {
        rel: "stylesheet"
        type: "text/css"
        href: "//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"
      }).appendTo('head')

    if AdminConfig.lazyLoad.fontawesome
      $("<link/>", {
        rel: "stylesheet"
        type: "text/css"
        href: "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"
      }).appendTo('head')
    
    @next()
```

I just wrote this from the top of my head, but this is how that PR could look like.

See [this](http://empire5.com/development/meteor-using-iron-router-to-conditionally-load-javascript-libraries/) and [this](http://stackoverflow.com/questions/14919894/getscript-but-for-stylesheets-in-jquery) for more info.

**Comment by Geen-Henk** [comment]
Made a PR #183

**Comment by sunstorymvp** [comment]
any news here? can't use this package because bootstrap styles leaks to the app...

**Comment by mpowaga** [comment]
The new version loads meteor-admin stylesheets lazily. It doesn't work for bootstrap files but we are working on this.

**Comment by evorel1** [comment]
has any progress been made on this?

**Comment by Levino** [comment]
Old topic. Still no solution?
