### ISSUE TITLE
Exception from Tracker recompute function: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by thomasspiesser** [yogiben/meteor-admin#280]
after update to 1.2., whenever i try and open any collection view from the dashboard i get:

<img width="1409" alt="bildschirmfoto 2015-09-28 um 15 25 06" src="https://cloud.githubusercontent.com/assets/4850200/10136538/5bde1d8e-65f5-11e5-8742-82c2b7bb597f.png">

any ideas?

**Comment by dtamburr** [comment]
I have the same message when opening any collection, plus this one when I open 'users':

```
Exception from Tracker recompute function:
debug.js:41 TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (native)
    at Function._.has (http://localhost:3000/packages/underscore.js?46eaedbdeb6e71c82af1b16f51c7da4127d6f285:1116:27)
    at Object.Blaze._lexicalBindingLookup (http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:3052:11)
    at Blaze.View.lookup (http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:3126:36)
    at Blaze.View.lookup (http://localhost:3000/packages/iron_dynamic-template.js?ee3a82d9513d6672d735cd269e5a228a8adb9247:777:23)
    at Template.adminUsersIsAdmin.Blaze.If.HTML.I.class (http://localhost:3000/packages/yogiben_admin.js?ee7caf095df475783863918a98e68ddeb03c2b4e:1050:40)
    at null.<anonymous> (http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:2674:44)
    at http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:1872:20
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:3671:12)
    at http://localhost:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:1870:29
```

I tried creating a new project and same issue.
Running meteor 1.2.0.1

**Comment by emiliano-viada-developer** [comment]
Same issue here!

**Comment by CaptainN** [comment]
Please clone (or checkout) my repo to your local packages directory and see if my fix works for you.

https://github.com/CaptainN/meteor-admin/

**Comment by pcorey** [comment]
@CaptainN Your fix mostly worked for me. I also had to remove the tailing `node` argument off of a few other Blaze calls in `startup.coffee`. Thanks!

**Comment by CaptainN** [comment]
Which ones (and what did it fix) - I'll update my PR.

**Comment by dtamburr** [comment]
Works for me. Thanks.

**Comment by CaptainN** [comment]
I updated my PR with the additional node changes, and synced with origin (and rebased, etc).

**Comment by amclin** [comment]
Thank you! I was banging my head (oooooooold meteor project with lots of issues to track down and replace) and I couldn't figure out why this package wasn't working!

**Comment by mochtu** [comment]
Awesome, that fix works like a charm! Thanks

**Comment by CaptainN** [comment]
I made two different PRs cause I confused myself. They both should end in the same result.

**Comment by robertclarkson** [comment]
I'm getting this as well

**Comment by mjsarfatti** [comment]
@CaptainN I can't figure out how to use your package instead of @yogiben's. in **/packages** I run
```$ git clone https://github.com/CaptainN/meteor-admin.git```
then ```$ meteor add yogiben:admin``` ?? I can't reliable resources online, everything I try either doesn't work or ends up using the original files.

**Comment by CaptainN** [comment]
create another folder inside packages, like packages/meteor-admin, then do you clone there.

**Comment by mjsarfatti** [comment]
Yes, but it's not working, it still recreates and uses the files from yogiben. I'm confused. This is what I tried:

    $ cd .meteor/local/build/programs/server/packages
    $ git clone https://github.com/CaptainN/meteor-admin.git [this creates a folder meteor-admin with your repo inside]
    $ meteor

and also:

    $ meteor remove yogiben:admin
    $ cd .meteor/local/build/programs/server/packages
    $ git clone https://github.com/CaptainN/meteor-admin.git [this creates a folder meteor-admin with your repo inside]
    $ meteor add yogiben:admin
    $ meteor

In both cases after running ```$ meteor``` the folder meteor-admin is deleted, and the file yogiben_admin is placed in /packages. But it's still Yogiben's file.

**Comment by CaptainN** [comment]
that's the wrong packages folder - create a new packages folder at the root of your application (next to lib, client, server, etc.) and clone in there.

**Comment by mjsarfatti** [comment]
I knew it was something stupid, it's working for me now! Thanks

**Comment by CaptainN** [comment]
np. :)

**Comment by rico-bee** [comment]
Works like a charm! thanks.

**Comment by Victordmdb** [comment]
Yep, this solved the issue, nice work!

**Comment by happy-dev** [comment]
Congrats! Many thanks

**Comment by obiwarn** [comment]
Awesome! This has to be integrated.

**Comment by marcovossen** [comment]
Thanks!
