### ISSUE TITLE
adding roles to a user

### ISSUE THREAD

**Issue by dcsan** [yogiben/meteor-admin#31]
you can toggle to *remove* admin, but it seems the functionality to add an admin role to a user doesn't work, unless i'm missing something obvious?

![image](https://cloud.githubusercontent.com/assets/514002/4767843/4362d0d6-5b62-11e4-9d09-2b5c89a488b7.png)

![image](https://cloud.githubusercontent.com/assets/514002/4767836/2db982de-5b62-11e4-9869-1b577c5ab334.png)

^^ no roles to click

**Comment by mordra** [comment]
actually, i had the same issue, but only with one user. I put it down to maybe you can't remove admin role from the logged in user? also had meteor toys with impersonation and haven't looked any further.
