### ISSUE TITLE
new release to atmosphere?

### ISSUE THREAD

**Issue by morgunder** [yogiben/meteor-admin#320]
i see there have been several recent checkins including the showInSidebar option.  but it doesn't look like its been released to atmosphere.  can you give us a heads up on your release schedule?  thx

**Comment by yogiben** [comment]
Published.

**Comment by morgunder** [comment]
thank you for the quick response.  i appreciate it.  have been enjoying your work and look forward to being able to provide some PR down the road.  

was wondering, is there a way that you can connect the releases in github with the releases on atmosphere?  maybe make a release here first then comment it with 'pushed out as yogiben:admin@1.2.6'.

if i had my own github project i'd probably know how to actually recommend you do it, but for now its just a question
