### ISSUE TITLE
Can't download css if app is not running on port 80

### ISSUE THREAD

**Issue by perusopersonale** [yogiben/meteor-admin#327]
Hi,
I've deploy an app  with mup on port 8000 and admin page is not working fine because app is not downloading the proper css.

http://xxx.xxx.xxx.xxx/packages/mfactory_admin-lte/css/skins/skin-black.min.css net::ERR_CONNECTION_TIMED_OUT
but it should be:

http://xxx.xxx.xxx.xxx:8000/packages/mfactory_admin-lte/css/skins/skin-black.min.css 

Is there a way to fix it?

**Comment by HelloYie** [comment]
+1  [http://localhost:3000/packages/yogiben_admin/lib/client/css/AdminLTE.min.css](http://localhost:3000/packages/yogiben_admin/lib/client/css/AdminLTE.min.css)

I cant't replace the root_url  `localhost:3000` to  ip: `10.xx.xx.xx:3000`.

**Comment by Kostanos** [comment]
I have the same issue. it seems that the hostname to get AdminLTE.css is coming from some variable.
It should be changed to relative path

**Comment by Kostanos** [comment]
I think I found it, it takes domain from ROOT_URL environment variable.

`ROOT_URL="https://<my host>"`

**Comment by perusopersonale** [comment]
good to know...my quick and dirt solution was to copy admin's css in app css:)
