### ISSUE TITLE
adminDashboardundefinedEdit

### ISSUE THREAD

**Issue by dladiguna** [yogiben/meteor-admin#351]
Hi, 
Thanks for the great package!
I'm learning meteorjs and I use meteor-admin as well as meteor tabular

I have a collection named friend that i want to be able to manage from my admin page:
```
AdminConfig = {
  name: 'Friend List',
  collections: {
    Friends:{}
  }
};
```
and I created another table for my users:
```
TabularTables ={};
TabularTables.Customers = new Tabular.Table({
  name: "Friends",
  collection: Friends,
  columns:[
     {data: "fullName", title: "Name"},
     {data: "phone1", title: "Phone"},
  ]
});
```
and in my html file:
`{{> tabular table=TabularTables.Friendsclass="table table-striped table-bordered table-condensed"}}`

If i do this, iron-core would throw me a warning and the table would not be displayed correctly(tabular would just shows id, edit button, and delete button). The warning seems to disappear when i remove the table either from my admin page or my userpage, and the table would be displayed correctly.

> You called Router.path for a route named "adminDashboardundefinedEdit" but that route doesn't seem to exist. Are you sure you created it?

<img width="696" alt="screen shot 2016-05-02 at 4 11 27 pm" src="https://cloud.githubusercontent.com/assets/11518394/14951076/a78c64f8-1080-11e6-9ef2-e8990d8be0bd.png">

I have never created/called adminDashboardundefinedEdit 
I am wondering if i used meteor-tabular/admin incorrectly or is this an issue?

Any hint would be appreciated, Thank you

**Comment by dladiguna** [comment]
Turned out meteor admin will create table using meteor-tabular based on the collection name
Changed the table name and it fixed the issue

**Comment by mOsCpU0** [comment]
Hi, @dladiguna,! I have the same problem!!!, can you tell me how did you solve it ?, Where does the name of the table change? please help me! :(

Thanks in Advance!
