### ISSUE TITLE
FR: way to imply relations

### ISSUE THREAD

**Issue by dcsan** [yogiben/meteor-admin#38]
(this maybe more an autoform issue?)

it would be great to have a way to create links for relations / related docs.
eg if i'm looking at a list of Players , and one field is "inventory" 
clicking on the entry would load the relevant record, eg 

`/admin/Players/`  -> links to 
`/admin/Inventory?player=123`

**Comment by obiwarn** [comment]
My auxCollections dont work anymore with the new version.

Did you change how to do relations?

**Comment by obiwarn** [comment]
Ah never mind. Found it.

Just use collection helpers for this.
