### ISSUE TITLE
Cannot create first admin user

### ISSUE THREAD

**Issue by drabiter** [yogiben/meteor-admin#44]
Hi,

I have created a JS file on the root containing
```
AdminConfig = {
  collections: {
    Posts: {}
  }
};
```
but when visiting `/admin` always getting **You need to be an admin to view this page**

**Comment by JunheeK** [comment]
@yogiben Thanks for creating this awesome admin UI for meteor! Disappointed by Houston's withdrawal, I'm so happy to find this package. Great job. Thanks.

However, I'm using Meteor 1.0.2.1 and experiencing same issue. When I put a very default setting as Readme.md says and go to /admin, all I see is just white screen. When I inspect it, it says 'You need to be an admin to view this page' but it doesn't show in browser.

I also installed your Meteor starterkit with admin, and found it's working properly. Is there any stuffs that I have to do to get admin UI working other than installing dependencies and setting adminConfig?

**Comment by yogiben** [comment]
Sorry for the late reply @JunheeK 

Check the readme for multiple ways to make a user admin.

You can also do it by settings `"roles": ["admin"]` in the db

**Comment by mohitag19** [comment]
If somebody else is stuck, then check out the answers on this one - https://github.com/yogiben/meteor-admin/issues/20

By the way, just manually editing my only user with this code worked for me
db.users.update({id: 'user-id-goes-here'},{$set: {roles: ['admin']}});
