### ISSUE TITLE
Question: Best way to go about adding a custom Dashboard.

### ISSUE THREAD

**Issue by rwatts3** [yogiben/meteor-admin#79]
Greetings, 

I have a question regarding which is the best way to go about adding a custom dashboard. 

Let's say there is a client that would like specific widgets to render in a separate section. Such as content related widgets, or settings type widgets where they can add settings that will add functionality to the blog. 

What is the best way about doing this. I know I could add a custom link called "Settings" , and add a route to /admin/settings/ . So how do I keep the same functionality as the original Dashboard, but make it so that widgets assigned to this area go to the /settings/ panel.

**Comment by yogiben** [comment]
Currently there are no previsions for the /admin widgets to be used on other pages. I think you'll have to hack it.
