### ISSUE TITLE
Request : Examples for Extending the Dashboard 

### ISSUE THREAD

**Issue by rwatts3** [yogiben/meteor-admin#87]
Please provide an example for how one could extend the admin dashboard.

Is it possible to create a secondary dashboard.  For instance let's say I want to create a replica of the dashboard at a path called /settings.  And only widgets relating to settings will go to that path.  So instead of going to / dashboard and having  a cluster of widgets on the main dash board.  I could add a custom link to settings.  And have all my widgets related to settings render in the settings route to logically separate the widgets.  Could you give me a code example of how I could do this the most efficient way ?   

Thank you.  

Ryan.

**Comment by yogiben** [comment]
Hoping to write a couple of blogs on the subject very soon.
