### ISSUE TITLE
New Green Icon in the Upper Right Corner

### ISSUE THREAD

**Issue by rwatts3** [yogiben/meteor-admin#93]
The new green Plus icon in the upper right corner of the collection layout view always points to /new/ post, it gives the indication that the user is able to create a new post, however it only goes to /posts/new .

**Comment by mpowaga** [comment]
It is already solved with [this](https://github.com/yogiben/meteor-admin/commit/dbebbaecbfd23a183f21aabbe1c65d27e7e55796) commit but not released yet.
